server:
  port: 9190
  
spring:
  zipkin:    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  jpa:    show-sql: true  
  datasource:
    url: jdbc:h2:mem:testdb
  test:
    database:
      replace: none
   
  application:    name: ORDER-SERVICE
    
logging:
  file:
    name: C:/Users/vicky/OneDrive/Desktop/Downloads/logs/microservice.log    
      
     